name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: gcp-project-452602

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push to Google Container Registry
        run: gcloud builds submit --config cloudbuild.yml .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy weather-app \
            --image us-central1-docker.pkg.dev/gcp-project-452602/weather-image/next-weather:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars NEXT_PUBLIC_GCP_API_KEY=${{ secrets.NEXT_PUBLIC_WEATHER_KEY }}
